### ISSUE TITLE
Format disconnect messages

### ISSUE THREAD

**Issue by zardoy** [zardoy/minecraft-web-client#26]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Funded-%2300A156.svg" />](https://oss.issuehunt.io/r/zardoy/prismarine-web-client/issues/26)

We already format chat & death messages. Let's refactor loading & error screen to React and use the same logic as for death screen, this should be easy. Also need to ensure that long kick messages are scrollable and don't overflow buttons (+ensure have global scroll bar styles).

examples. This is not readable at all:

![image](https://github.com/zardoy/prismarine-web-client/assets/46503702/0ca0a54c-316d-487c-a131-87f453820961)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [<img src='https://avatars.githubusercontent.com/u/46503702?v=4' alt='zardoy' width=24 height=24> zardoy](https://oss.issuehunt.io/u/zardoy) ($50.00)

### Tips

- Checkout the [Issuehunt explorer](https://oss.issuehunt.io/r/zardoy/prismarine-web-client/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://oss.issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by raghavpatidar** [comment]
I want to work on this issue can you help me how to approach initially

**Comment by zardoy** [comment]
Hey @raghavpatidar! To reproduce:
- On the prod website:
1. Connect to `mc.gamster.org`
- Locally:
1. Start npm script `test-mc-server`
2. Start npm script `start`
3. open localhost:8080
4. connect to server by ip localhost
5. In terminal with npm script `test-mc-server` write `kick <player name>` like `kick testbot`

You should see raw JSON text displayed, instead the json should be parsed and used with `MessageFormattedString.tsx` (from next branch)

I was adding storybook support on the `next` branch, so it's easier to develop React components. You can see how DeathScreen is used in combination with StoryBook: https://github.com/zardoy/prismarine-web-client/blob/d77484c9662819edda8fe88424e9ea0190bd152b/src/react/DeathScreen.stories.tsx#L24-L25 You might want to do new React component in the same fashion (I mean refactor [loading_or_error_screen.js](https://github.com/zardoy/prismarine-web-client/blob/1935c9d173f22cfa9376643eecbf3010f5daabbd/src/menus/loading_or_error_screen.js#L13))

**Comment by zardoy** [comment]
Sorry for the delay. In MC version plays a crucial role, open mc server file - just because it set to run with version 1.16.1, it runs with version 1.16.1. And here you are connecting from the web client with version 1.18.1. Another question is why auto-version doesn't work sometimes and there is no proper error message when you connect to flying-squid. I think most probably there is an issue specific to flying-squid js impl, need to look into protocol stuff because I definitely remember I didn't have such issues with native java servers. Flying squid is totally okay for simple testing as it is fast & portable, but of course, for bigger testing or adding more serious features I always use native servers remotely/locally.

**Comment by zardoy** [comment]
test fund
